#!/bin/bash
# nohup with no input & output to 'nohup.out'
# 2018-10-09 written by Lydia
# 2019-03-02 modified by Lydia
#######################################################################|
# nohup "$*" > nohup.out < /dev/null 2>&1 &
rm -f nohup.out
unbuf=''
if [ -n "$(which unbuffer 2> /dev/null)" ]; then unbuf=unbuffer; fi
nohup ${unbuf} bash -c "$*" &
pid=$!
ps Op $pid
echo '-----------------------------------'
echo -e "Type to check:\nps Op $pid"
