#!/bin/bash
# Loop a script or any command
# 2017-11-05 written by Lydia
# 2017-12-19 modified by Lydia
#######################################################################|
dt=10
cmd=''
a=''
usage="USAGE: loop N(<=0 means infinite) [dt] '...'"
#######################################################################|
if [ "$1" = 'h' ]; then echo $usage; exit 1; fi
if [[ "$1" =~ ^-?[0-9]+$ ]]; then loop=$(echo $1 | awk '{printf "%d\n",$1}'); shift
else echo $usage; exit 1
fi
if [ ${loop} -le 0 ]; then
  imax=1; echo -e '###### Infinite loop ######\n'
else
  imax=${loop}; echo -e "###### Loop = ${imax} ######\n"
fi
if [[ "$1" =~ ^[0-9]+$ ]]; then dt=$(echo $1 | awk '{printf "%d\n",$1}'); shift; fi
cmd=$*
if [ -z "${cmd}" ]; then echo $usage; exit 1; fi
#######################################################################|
i=0
while [ $i -lt ${imax} ]; do
  bash -c "${cmd}"
  if [ ${loop} -gt 0 ]; then i=$(($i+1)); else i=0; fi
  if [[ ${dt} -gt 1 && $i -lt ${imax} ]]; then
    t=0
    while [ $t -lt ${dt} ]; do
      if [ $t -eq 0 ]; then
        echo -en '\nWaiting... -'
      else
        if [ $(echo "$t%4" | bc) -eq 1 ]; then
          echo -en '\b\'
        elif [ $(echo "$t%4" | bc) -eq 2 ]; then
          echo -en '\b|'
        elif [ $(echo "$t%4" | bc) -eq 3 ]; then
          echo -en '\b/'
        else
          echo -en '\b-'
        fi
      fi
      sleep 1; t=$(($t+1))
    done
    if [ ${loop} -gt 0 ]; then
      echo -e "\b\b\b\b\b\b\b\b\b\b\b\b------ Rerun($i/${imax}) ------"
    else
      echo -e "\b\b\b\b\b\b\b\b\b\b\b\b------ Rerun ------"
    fi
  fi
done
######################################################################################|
exit 0
