#!/bin/bash
# Loop a script or any command
# 2017-11-05 written by Lydia
# 2018-05-21 modified by Lydia
#######################################################################|
dt=10
waitdt=0.25
cmd=''
a=''
loop=-1
usage="USAGE: $(basename $0) N [dt] 'COMMAND'\n \
\tN: number of loops (default or N < 0: loop forever)\n \
\tdt: wait seconds (default: 10)"
#######################################################################|
if [ "$1" = 'h' ]; then echo -e $usage; exit 1; fi
if [[ "$1" =~ ^-?[0-9]+$ ]]; then loop=$(echo $1 | awk '{printf "%d\n",$1}'); shift
fi
if [ ${loop} -le 0 ]; then
  imax=1; echo -e '------ loop ------\n'
else
  imax=${loop}; echo -e "------ 1/${imax} ------\n"
fi
if [[ "$1" =~ ^[0-9]+$ ]]; then dt=$(echo $1 | awk '{printf "%d\n",$1}'); shift; fi
dt=$((dt*4))
cmd=$*
if [ -z "${cmd}" ]; then echo $usage; exit 1; fi
#######################################################################|
i=1
indicator=('-' '\' '|' '/')
while [ $i -le ${imax} ]; do
  bash -c "${cmd}"
  if [ ${loop} -gt 0 ]; then i=$(($i+1)); else i=1; fi
  if [[ ${dt} -gt 1 && $i -le ${imax} ]]; then
    t=0
    while [ $t -lt ${dt} ]; do
      if [ $t -eq 0 ]; then
        echo -en "\nWaiting... ${indicator[0]}"
      else
        for j in ${!indicator[@]}; do
          if [ $(echo "$t%${#indicator[@]}" | bc) -eq $j ]; then
            echo -en "\b${indicator[j]}"; break
          fi
        done
      fi
      sleep ${waitdt}; t=$(($t+1))
    done
    if [ ${loop} -gt 0 ]; then
      echo -e "\r------ $i/${imax} ------"
    else
      echo -e "\r------------------------"
    fi
  fi
done
#######################################################################|
exit 0
